### ISSUE TITLE
add default navigation links to devise

### ISSUE THREAD

**Issue by yshmarov** [abhaynikam/boring_generators#34]
something like this to go into `application.html.erb` before `yield`. What do you think?
```
<% if current_user %>
  <%= link_to current_user.email, edit_user_registration_path %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %>
  <%= link_to "Register", new_user_registration_path %>
<% end %>
```

**Comment by abhaynikam** [comment]
Thanks for reporting the issue @yshmarov 😊. Currently, I think the install generator should only install the devise and not do additional customization to the application. I am opt-out of this because not all user(80%) would want to have customization to the application layout. This also adds an extra task of debugging and removing the code for those user who do not want this change. 

Maybe if we see more such request coming we can surely consider it in the future. Closing this issue for now and keeping the generator simple 😊
